### ISSUE TITLE
.NET 4.5 is EOL

### ISSUE THREAD

**Issue by PrincessRTFM** [Arkhist/Hacknet-Pathfinder#153]
This project still targets the .NET Framework 4.5, which is officially unsupported. Additionally, it's old enough that some commonly used modern features aren't available, such as tuples. Ideally, it would be best to move to version 5, but at least 4.8 would put it back in the territory of supported framework versions.

**Comment by Fayti1703** [comment]
> However, Linux releases of Hacknet bundle their own mono runtime (on framework 4.5 or 4, I forgot)

The bundled framework version is .NET 4.0, which we currently bump up to .NET 4.5 via internal Mono hacks. Not sure how much effort it would take to bump to a higher version.

**Comment by Windows10CE** [comment]
I'm unsure how much you know about the .NET ecosystem, but .NET 5 is not a version of .NET Framework, and runs on a completely different runtime. This isn't feasible to change to due to how Hacknet is built on MonoKickstart. We also can't go up to netfx 4.8, because Mono doesn't have support for that framework version. So that leaves the latest we can go to being 4.7.2 as far as I know.

Also, it's not really important to the main point here, but for completeness.
> Additionally, it's old enough that some commonly used modern features aren't available, such as tuples.
I'm unsure what features you're talking about besides tuples, and tuples actually *are* usable if you write your own version of the ValueTuple structs. The main problem here is that this project isn't able to compile with VS2022 since they dropped support for this version lmao

**Comment by Windows10CE** [comment]
Fixed with 98c09314282a81593b58f11205a9d811352ae1e7
