### ISSUE TITLE
Reimplement important patches in Harmony

### ISSUE THREAD

**Issue by Windows10CE** [Arkhist/Hacknet-Pathfinder#61]
Harmony is easier to read and write than the raw Mono.Cecil patches, and they should be easier for plugin developers to understand when they need to reference the PF source.
- [x] Catalog the intentions of every patch in Pathfinder/PathfinderHooks.cs
- [ ] Cull unused or unnecessary patches
- [ ] Reimplement in in Harmony
- [ ] Implement some new patches previously not feasible where they would be useful

**Comment by Fayti1703** [comment]
A list of every patch, along with some descriptions and what events they fire.

| Name | Description | Event | Second Event |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|-------------------------------|--------------------------|
| [onMain](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L34)                       | Grab launch options, initialize Pathfinder                                                                             | StartUpEvent                  |                          |
| [onLoadContent](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L83)                | Load mod content                                                                                                       | GameLoadContentEvent          |                          |
| [onCommandSent](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L97)                | State updates based on events                                                                                          | CommandSentEvent              | CommandFinishedEvent     |
| [onCommandFinished](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L132)           |                                                                                                                        | CommandFinishedEvent          |                          |
| [onOSDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L145)                    | Reimplementation of rendering logic                                                                                    | OSStartDrawEvent              | OSEndDrawEvent           |
| [onLoadSession](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L265)               |                                                                                                                        | OSLoadContentEvent            |                          |
| [onUnloadSession](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L275)             |                                                                                                                        | OSUnloadContentEvent          |                          |
| [onMainMenuDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L282)              | + Fade on event cancel                                                                                                   | DrawMainMenuEvent             |                          |
| [onMainMenuButtonsDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L300)       |                                                                                                                        | DrawMainMenuButtonsEvent      |                          |
| [onLoadSaveFile](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L312)              |                                                                                                                        | OSLoadSaveFileEvent           |                          |
| [onSaveFile](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L333)                  |                                                                                                                        | OSSaveFileEvent               |                          |
| [onSaveWrite](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L346)                 |                                                                                                                        | OSSaveWriteEvent              |                          |
| [onLoadNetmapContent](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L353)         |                                                                                                                        | NetworkMapLoadContentEvent    |                          |
| [onExecutableExecute](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L368)         | For all programs                                                                                                       | ExecutableExecuteEvent        |                          |
| [onPortExecutableExecute](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L397)     | For port crackers                                                                                                      | ExecutablePortExecuteEvent    |                          |
| [onLoadSavedComputerStart](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L419)    |                                                                                                                        | LoadSavedComputerStartEvent   |                          |
| [onLoadSavedComputerEnd](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L438)      |                                                                                                                        | LoadSavedComputerEndEvent     |                          |
| [onLoadContentComputerStart](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L449)  |                                                                                                                        | LoadContentComputerStartEvent |                          |
| [onLoadContentComputerEnd](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L474)    |                                                                                                                        | LoadContentComputerEndEvent   |                          |
| [onDrawMainMenuTitles](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L530)        | Reimplementation of title draw, pathfinder addition                                                                    | DrawMainMenuTitlesEvent       |                          |
| [onGameUnloadContent](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L584)         |                                                                                                                        | GameUnloadContentEvent        |                          |
| [onGameUpdate](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L591)                |                                                                                                                        | GameUpdateEvent               |                          |
| [onPortNameDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L597)              | Custom port handling                                                                                                   |                               |                          |
| [onDisplayModuleUpdate](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L627)       |                                                                                                                        | DisplayModuleUpdateEvent      |                          |
| [onDisplayModuleDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L637)         |                                                                                                                        | DisplayModuleDrawEvent        |                          |
| [onExtensionsMenuScreenDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L650)  |                                                                                                                        | DrawExtensionMenuEvent        |                          |
| [onExtensionsMenuListDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L664)    |                                                                                                                        | DrawExtensionMenuListEvent    |                          |
| [onOptionsMenuDraw](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L680)           |                                                                                                                        | OptionsMenuDrawEvent          |                          |
| [onOptionsMenuLoadContent](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L694)    |                                                                                                                        | OptionsMenuLoadContentEvent   |                          |
| [onOptionsMenuUpdate](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L701)         |                                                                                                                        | OptionsMenuUpdateEvent        |                          |
| [onOptionsApply](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L711)              |                                                                                                                        | OptionsMenuApplyEvent         |                          |
| [onLoadRunnableActionsIntoOS](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L719) |                                                                                                                        | ActionsLoadIntoOSEvent        |                          |
| [onSCInstantlyCheck](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L733)          | Bug-fix Hacknet's `Instantly@needsMissionComplete` check                                                               |                               |                          |
| [onSCConnectCheck](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L753)            | Bug-fix Hacknet's `OnConnect@needsMissionComplete` check (potential philosphical debate)                               |                               |                          |
| [onFilterString](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L788)              | Replace Hacknet's filter system with our own                                                                           |                               |                          |
| [onAppendToErrorFile](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L795)         | Display errors logged by base function in the console -- they're otherwise ignored on non-Windows platforms                     |                               |                          |
| [onTerminalWriteAppend](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L801)       |                                                                                                                        | TerminalWriteEvent            | TerminalWriteAppendEvent |
| [onTerminalWriteLine](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L822)         |                                                                                                                        | TerminalWriteEvent            | TerminalWriteLineEvent   |
| [onTerminalWriteAppendEnd](https://github.com/Arkhist/Hacknet-Pathfinder/blob/3c7b95357f945502928c3e411749bf525d413fb1/Pathfinder/PathfinderHooks.cs#L842)    | Companion for onTerminalWriteAppend. Unsets the flag that causes onTerminalWriteLine to not fire a TerminalWriteEvent |                               |                          |

**Comment by Windows10CE** [comment]
Although many of these are still missing from the rewrite, it's hard to determine which of these would really see any use, and since developers have the ability to hook into things themselves I think the plugin-centric ones would just clutter the API. I'll add more as things go and people ask, but overall I don't plan on explicitly bringing back events/patches just because Pathfinder 3/4 used them. With that being said, there isn't much of a reason to keep this open if it's just going to be unused, so I'll close it.
